<?php

namespace App\QuickScan;

use App\Models\QuickScan\QuickScanWorkspace;
use App\Models\User;

final class QuickScanSyntheticFixture
{
    public function __construct(
        private readonly QuickScanAccess $access,
        private readonly QuickScanIngestion $ingestion,
        private readonly QuickScanAnalysis $analysis,
        private readonly QuickScanAudit $audit,
    ) {}

    /** @return array{scan:QuickScanWorkspace,token:string} */
    public function create(User $actor, int $contacts = 500): array
    {
        $contacts = max(1, min(500, $contacts));
        $created = $this->access->create([
            'garage_name' => 'Synthetic Quick Scan Garage '.now()->format('Ymd-His'),
            'garage_contact_name' => 'Synthetic Decision Maker',
            'garage_phone' => '+971 50 000 9900',
            'garage_email' => 'quick-scan-'.now()->format('YmdHis').'@staging.sayaraforce.test',
            'source' => 'synthetic_staging_uat',
            'notes' => 'Generated by the staging-only deterministic Quick Scan fixture.',
        ], $actor);
        $scan = $created['scan'];
        $scan->forceFill([
            'consent_at' => now(),
            'consent_policy_version' => (string) config('quick_scan.consent_policy_version'),
            'connection_mode' => 'business_app_onboarding',
            'claimed_whatsapp_number' => '+971500009900',
            'claimed_whatsapp_hash' => $this->ingestion->identityHash($scan, '971500009900'),
            'status' => 'history_syncing',
            'connected_at' => now(),
        ])->save();
        $this->audit->record($scan, 'quick_scan.synthetic_connection_ready', $actor, [
            'status' => 'history_syncing', 'count' => $contacts,
        ]);

        $payload = ['status' => 'completed', 'history' => [[
            'status' => 'completed', 'threads' => $this->threads($contacts),
        ]]];
        $scan = $this->ingestion->ingest($scan, $payload, true);
        $scan = $this->analysis->run($scan, allowExternalAi: false);

        return ['scan' => $scan, 'token' => $created['token']];
    }

    private function threads(int $contacts): array
    {
        $threads = [];
        for ($index = 1; $index <= $contacts; $index++) {
            $phone = '97155'.str_pad((string) $index, 7, '0', STR_PAD_LEFT);
            [$body, $days] = match ($index % 10) {
                0 => ['How much is a brake service quote? Please send the price.', 120],
                1 => ['I need an oil service for my Toyota. Can you help?', 95],
                2 => ['Thank you, the service completed and I collected the car.', 45],
                3 => ['Family dinner this weekend, love you.', 20],
                4 => ['Move the vehicle to bay 2 for the mechanic shift.', 15],
                5 => ['Hello there.', 70],
                6 => ['Battery diagnostic and repair appointment please.', 10],
                7 => ['Can I get a quotation for tyres?', 75],
                8 => ['I need a booking for my Nissan service tomorrow.', 3],
                default => ['What is the cost of an AC repair?', 62],
            };
            $threads[] = [
                'wa_id' => $phone,
                'profile' => ['name' => 'Synthetic Contact '.$index],
                'messages' => [[
                    'id' => 'synthetic.quick-scan.'.$index,
                    'type' => 'text', 'text' => ['body' => $body],
                    'timestamp' => (string) now()->subDays($days)->timestamp,
                ]],
            ];
        }

        return $threads;
    }
}
