<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}"><meta name="robots" content="noindex,nofollow">
    <title>WhatsApp Opportunity Scan — SayaraForce</title>
    @vite(['resources/css/app.css', 'resources/js/app.jsx'])
    <style>
        body{background:#07112a;color:#f8fafc}.qs-shell{background:radial-gradient(circle at 15% 5%,rgba(255,106,0,.2),transparent 34%),#07112a}.qs-card{background:rgba(13,27,61,.88);border:1px solid rgba(255,255,255,.1);box-shadow:0 24px 70px rgba(0,0,0,.25)}.qs-muted{color:#aebbd0}.qs-metric{background:linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.035));border:1px solid rgba(255,255,255,.1)}@media print{.no-print{display:none!important}body,.qs-shell{background:#fff;color:#111}.qs-card,.qs-metric{background:#fff;color:#111;box-shadow:none;border-color:#ddd}.qs-muted{color:#475569}}
    </style>
</head>
<body class="qs-shell min-h-screen antialiased">
<header class="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><img src="{{ asset('images/brand/sayaraforce-logo-horizontal.png') }}" alt="SayaraForce" class="h-10 w-auto"><span class="rounded-full border border-orange-400/30 bg-orange-500/10 px-3 py-1 text-xs font-black uppercase tracking-[.18em] text-orange-300">Quick Scan</span></header>
<main class="mx-auto max-w-6xl px-5 pb-16 sm:px-8">
    @if($scan->status === 'consent_pending')
        <section class="qs-card overflow-hidden rounded-[2rem] p-6 sm:p-10 lg:p-14">
            <p class="text-xs font-black uppercase tracking-[.22em] text-orange-300">WhatsApp Business Opportunity Scan</p>
            <h1 class="mt-5 max-w-4xl text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">See what opportunities may already exist in your conversations.</h1>
            <p class="qs-muted mt-5 max-w-3xl text-base font-semibold leading-8 sm:text-lg">SayaraForce will temporarily analyse supported WhatsApp Business history for customer conversations, enquiries, quotes and retention opportunities worth reviewing.</p>
            <div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Likely customer conversations','Potential missed enquiries','Retention opportunities','Quotes worth reviewing'] as $item)<div class="qs-metric rounded-2xl p-4 text-sm font-black"><span class="mr-2 text-emerald-400">✓</span>{{ $item }}</div>@endforeach</div>
            <div class="mt-8 rounded-2xl border border-emerald-400/20 bg-emerald-500/8 p-5"><h2 class="font-black text-emerald-200">Read-only and temporary</h2><ul class="qs-muted mt-3 grid gap-2 text-sm font-semibold sm:grid-cols-2"><li>We do not message your customers</li><li>We do not create campaigns</li><li>We do not change your WhatsApp Business account</li><li>Customer-level data is removed if you do not continue</li></ul></div>
            <form method="POST" action="{{ route('quick-scan.consent', ['token'=>$token]) }}" class="mt-8 grid gap-5 sm:grid-cols-2">@csrf
                <label class="text-sm font-bold">WhatsApp Business number<input name="whatsapp_number" required placeholder="+971 50 000 0000" class="mt-2 w-full rounded-xl border border-white/15 bg-[#09142e] px-4 py-3"></label>
                <label class="text-sm font-bold">How you use the number<select name="connection_mode" class="mt-2 w-full rounded-xl border border-white/15 bg-[#09142e] px-4 py-3"><option value="business_app_onboarding">Keep using WhatsApp Business App</option><option value="cloud_api">Dedicated WhatsApp number</option></select></label>
                <label class="sm:col-span-2 text-sm font-bold">Team numbers to exclude (optional)<textarea name="staff_numbers" rows="2" placeholder="One number per line" class="mt-2 w-full rounded-xl border border-white/15 bg-[#09142e] px-4 py-3"></textarea></label>
                <label class="sm:col-span-2 flex items-start gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm leading-6 qs-muted"><input type="checkbox" name="consent" value="1" required class="mt-1"><span>I understand SayaraForce will temporarily process supported WhatsApp history for an AI-assisted opportunity assessment. Suggestions are not guaranteed conclusions. No customer will be contacted, and customer-level data follows the Quick Scan deletion policy if we do not continue.</span></label>
                <button class="sm:col-span-2 rounded-xl bg-orange-500 px-6 py-4 text-base font-black text-white">I understand and continue</button>
            </form>
        </section>
    @elseif($scan->status === 'connection_pending')
        @php($metaConfig = $metaConfigurations[$scan->connection_mode] ?? [])
        <section class="qs-card mx-auto max-w-3xl rounded-[2rem] p-6 sm:p-10">
            <p class="text-xs font-black uppercase tracking-[.22em] text-orange-300">Secure connection</p><h1 class="mt-4 text-4xl font-black">Connect WhatsApp with Meta</h1>
            <ol class="mt-7 grid gap-3 text-sm font-bold"><li class="qs-metric rounded-xl p-4">1. Consent recorded <span class="float-right text-emerald-400">Complete</span></li><li class="qs-metric rounded-xl p-4">2. WhatsApp number approved <span class="float-right text-emerald-400">Complete</span></li><li class="qs-metric rounded-xl p-4">3. Meta verification <span class="float-right text-amber-300">Pending</span></li><li class="qs-metric rounded-xl p-4">4. Supported history scan <span class="float-right qs-muted">Waiting</span></li></ol>
            <div id="quickScanAlert" class="mt-5 hidden rounded-xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-200"></div>
            @if($metaConfig['is_configured'] ?? false)<button id="connectMeta" class="mt-7 w-full rounded-xl bg-orange-500 px-6 py-4 text-base font-black">Connect with Meta</button>@else<div class="mt-7 rounded-2xl border border-amber-400/25 bg-amber-500/10 p-5 text-sm font-bold text-amber-100">Meta connection is not configured for this staging environment yet. Your consent and number are saved safely; no provider state was fabricated.</div>@endif
        </section>
    @elseif(in_array($scan->status, ['history_syncing','analysing']))
        <section class="qs-card mx-auto max-w-3xl rounded-[2rem] p-6 text-center sm:p-10"><div class="mx-auto h-14 w-14 animate-spin rounded-full border-4 border-white/15 border-t-orange-500"></div><h1 class="mt-6 text-4xl font-black">Preparing your opportunity scan</h1><p class="qs-muted mt-3 text-base font-semibold">Only committed provider and analysis progress is shown.</p><div class="mt-8 grid grid-cols-2 gap-4"><div class="qs-metric rounded-2xl p-5"><div id="discovered" class="text-4xl font-black">{{ number_format($scan->contacts_discovered) }}</div><div class="qs-muted mt-2 text-xs font-black uppercase">Discovered</div></div><div class="qs-metric rounded-2xl p-5"><div id="analysed" class="text-4xl font-black">{{ number_format($scan->contacts_analysed) }}</div><div class="qs-muted mt-2 text-xs font-black uppercase">Analysed</div></div></div></section>
    @elseif(in_array($scan->status, ['report_ready','accepted','declined']))
        @php($m=(array)$scan->report_metrics)
        <section class="qs-card overflow-hidden rounded-[2rem] p-6 sm:p-10 lg:p-12">
            <div class="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-xs font-black uppercase tracking-[.22em] text-orange-300">Your WhatsApp Opportunity Scan</p><h1 class="mt-3 text-4xl font-black sm:text-5xl">{{ number_format((int)($m['conversations_analysed']??0)) }} conversations analysed</h1><p class="qs-muted mt-3 font-semibold">Results are evidence-led suggestions from the analysed sample, not guaranteed business outcomes.</p></div><button onclick="window.print()" class="no-print rounded-xl border border-white/15 px-5 py-3 text-sm font-black">Print summary</button></div>
            <div class="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Likely customer conversations',$m['likely_customers']??0,'text-sky-300'],['Potential retention customers',$m['retention_customers']??0,'text-emerald-300'],['High retention opportunities',$m['high_retention']??0,'text-orange-300'],['Potential missed enquiries',$m['potential_missed']??0,'text-amber-300'],['Quotes worth reviewing',$m['quotes_worth_reviewing']??0,'text-violet-300'],['Service-related conversations',$m['service_related']??0,'text-cyan-300'],['Insufficient evidence',$m['insufficient_evidence']??0,'text-slate-300'],['Personal / staff / noise',$m['personal_staff_noise']??0,'text-slate-400']] as [$label,$value,$colour])<article class="qs-metric rounded-2xl p-5"><div class="text-4xl font-black {{ $colour }}">{{ number_format((int)$value) }}</div><div class="qs-muted mt-3 text-sm font-bold">{{ $label }}</div></article>@endforeach</div>
            @if(!empty($m['evidence']))<div class="mt-8"><h2 class="text-2xl font-black">What is worth reviewing</h2><div class="mt-4 grid gap-4 lg:grid-cols-3">@foreach($m['evidence'] as $e)<article class="qs-metric rounded-2xl p-5"><div class="text-xs font-black uppercase text-orange-300">{{ $e['category'] }}</div><div class="mt-2 font-black">{{ $e['identity'] }}</div><p class="qs-muted mt-2 text-sm leading-6">{{ $e['summary'] }}</p></article>@endforeach</div></div>@endif
            <div class="mt-8 rounded-3xl border border-orange-400/25 bg-orange-500/10 p-6 sm:p-8"><h2 class="text-2xl font-black">Turn reviewed conversations into a structured customer workflow.</h2><p class="qs-muted mt-3 max-w-3xl text-sm font-semibold leading-6">Starting SayaraForce creates normal onboarding only. It does not charge you or import customers. Your garage administrator must still choose Track or Don't Track before any Client is created.</p>@if($scan->status==='report_ready')<div class="no-print mt-5 flex flex-col gap-3 sm:flex-row"><form method="POST" action="{{ route('quick-scan.accept',['token'=>$token]) }}">@csrf<button class="w-full rounded-xl bg-orange-500 px-6 py-4 font-black sm:w-auto">Start with SayaraForce</button></form><form method="POST" action="{{ route('quick-scan.decline',['token'=>$token]) }}">@csrf<button class="w-full rounded-xl border border-white/15 px-6 py-4 font-black sm:w-auto">Not now</button></form></div>@elseif($scan->status==='declined')<p class="mt-5 font-black text-amber-200">Customer-level scan data is scheduled for removal according to the Quick Scan policy.</p>@else<p class="mt-5 font-black text-emerald-200">Normal SayaraForce onboarding is ready.</p>@endif</div>
        </section>
    @elseif($scan->status === 'failed')
        <section class="qs-card mx-auto max-w-2xl rounded-[2rem] p-8 text-center"><h1 class="text-3xl font-black">We couldn't complete the WhatsApp history scan.</h1><p class="qs-muted mt-4">Nothing was sent to customers and no CRM records were created. Contact SayaraForce to retry safely.</p></section>
    @endif
</main>
@if($scan->status === 'connection_pending' && (($metaConfigurations[$scan->connection_mode]['is_configured'] ?? false)))
<script>
(()=>{const cfg=@json($metaConfigurations[$scan->connection_mode]);const csrf=@json(csrf_token());const token=@json($token);let active=null,code=null,session=null,busy=false;const alert=document.getElementById('quickScanAlert');const fail=m=>{alert.textContent=m;alert.classList.remove('hidden')};const trusted=o=>{try{const u=new URL(o);return u.protocol==='https:'&&(u.hostname==='facebook.com'||u.hostname.endsWith('.facebook.com'))}catch{return false}};const finish=async()=>{if(!active||!code||!session||busy)return;busy=true;try{const r=await fetch(`/scan/${token}/meta/complete`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify({code,state:active.state,session_event:session.event,business_id:session.data.business_id||null,waba_id:session.data.waba_id||null,phone_number_id:session.data.phone_number_id||null})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'The scan connection could not be completed.');location.reload()}catch(e){busy=false;fail(e.message)}};addEventListener('message',e=>{if(!active||!trusted(e.origin))return;let m=e.data;try{if(typeof m==='string')m=JSON.parse(m)}catch{return}if(!m||m.type!=='WA_EMBEDDED_SIGNUP')return;if(['CANCEL','ERROR'].includes(m.event)){fail('Meta onboarding did not complete. Nothing was connected.');return}session={event:m.event,data:m.data||{}};finish()});window.fbAsyncInit=()=>FB.init({appId:cfg.app_id,autoLogAppEvents:false,xfbml:false,version:cfg.graph_version});const s=document.createElement('script');s.async=true;s.defer=true;s.crossOrigin='anonymous';s.src='https://connect.facebook.net/en_US/sdk.js';document.head.appendChild(s);document.getElementById('connectMeta').addEventListener('click',async()=>{try{const r=await fetch(`/scan/${token}/meta/start`,{method:'POST',credentials:'same-origin',headers:{'Accept':'application/json','X-CSRF-TOKEN':csrf}});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'Could not start Meta connection.');active={state:d.state};FB.login(x=>{if(!x?.authResponse?.code){fail('Meta did not grant temporary authorization.');return}code=x.authResponse.code;finish()},{config_id:d.configuration.config_id,response_type:'code',override_default_response_type:true,extras:d.configuration.extras})}catch(e){fail(e.message)}})})();
</script>
@elseif(in_array($scan->status,['history_syncing','analysing']))
<script>setInterval(async()=>{const r=await fetch(@json(route('quick-scan.progress',['token'=>$token])),{headers:{Accept:'application/json'}});if(!r.ok)return;const d=await r.json();document.getElementById('discovered').textContent=Number(d.contacts_discovered).toLocaleString();document.getElementById('analysed').textContent=Number(d.contacts_analysed).toLocaleString();if(d.report_ready)location.reload()},3000)</script>
@endif
</body></html>
